version: '2'
services:
  postgres:
    image: postgres:9.6.1-alpine
  pact-broker:
    image: dius/pact-broker:2.35.0-1
    links:
      - postgres
    environment:
      - PACT_BROKER_DATABASE_HOST=postgres
      - PACT_BROKER_DATABASE_USERNAME=postgres
    ports:
      - "80:80"
